function d=mydialog
d = dialog('Position',[300 300 250 150],'Name','My Dialog','WindowStyle','normal');

uicontrol('Parent',d,...
    'Style','text',...
    'Position',[20 80 210 40],...
    'String','Click the close button when you''re done.');

uicontrol('Parent',d,...
    'Position',[85 20 70 25],...
    'String','Close',...
    'Callback','delete(gcf)');
end

